name: Fourth Workflow
on: 
    workflow_run:
      workflows: ["Third Workflow"]
      types:
        - completed

jobs:
    success-world-command:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
        - name: Successful Workflow Run
          run: echo "Success! The previous workflow completed successfully."
    failure-world-command:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'failure' }}
      steps:
        - name: Failed Workflow Run
          run: echo "Failure! The previous workflow did not complete successfully."
