name: Third Workflow
on: push
jobs:
    run-first-command:
      runs-on: ubuntu-latest
      steps:
        - name: Comand in Multiple
          
          run: |
            echo "my relative path: "
            pwd
            echo "my catalog path: "
            ls -la
        - uses: actions/checkout@v4
        # - name: copy files
        #   run: |
        #     git init
        #     git remote add origin "https://github.com/actions/checkout.git"
        #     git fetch
        #     git checkout main
        - name: new file
          run: |
            echo "my new ls -a: "
            ls -asdasdas

